In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\user\my_snippet\DataSets\TB_Burden_Country.csv")

df.head()

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AF,AFG,4,EMR,1990,11731193,306.0,156.0,506.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AF,AFG,4,EMR,1991,12612043,343.0,178.0,562.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AF,AFG,4,EMR,1992,13811876,371.0,189.0,614.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,EMR,1993,15175325,392.0,194.0,657.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,EMR,1994,16485018,410.0,198.0,697.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN

In [9]:
# cleaning
nulls = df.isnull().sum()
df = df.dropna(subset=['Country or territory name'])
duplicates = df.duplicated().sum()#0
print(f'Null Values: {nulls[nulls>0]},\
      Duplicates: {duplicates}')

Null Values: ISO 2-character country/territory code                                                        24
Estimated prevalence of TB (all forms) per 100 000 population, low bound                      20
Estimated prevalence of TB (all forms) per 100 000 population, high bound                     20
Estimated prevalence of TB (all forms), low bound                                             20
Estimated prevalence of TB (all forms), high bound                                            20
Estimated mortality of TB cases who are HIV-positive, per 100 000 population, low bound     1942
Estimated mortality of TB cases who are HIV-positive, per 100 000 population, high bound    1942
Estimated number of deaths from TB in people who are HIV-positive, low bound                1942
Estimated number of deaths from TB in people who are HIV-positive, high bound               1942
Estimated incidence (all forms) per 100 000 population, low bound                             94
Estimated incidence (all forms) per 100 000 population, high bound                            94
Estimated number of incident cases (all forms), low bound                                     94
Estimated number of incident cases (all forms), high bound                                    94
Method to derive incidence estimates                                                        2133
Estimated HIV in incident TB (percent)                                                      1475
Estimated HIV in incident TB (percent), low bound                                           1478
Estimated HIV in incident TB (percent), high bound                                          1478
Estimated incidence of TB cases who are HIV-positive per 100 000 population                 1475
Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound      1478
Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound     1478
Estimated incidence of TB cases who are HIV-positive                                        1475
Estimated incidence of TB cases who are HIV-positive, low bound                             1478
Estimated incidence of TB cases who are HIV-positive, high bound                            1478
Method to derive TBHIV estimates                                                            5120
Case detection rate (all forms), percent                                                     449
Case detection rate (all forms), percent, low bound                                          449
Case detection rate (all forms), percent, high bound                                         449
dtype: int64,      Duplicates: 0

In [14]:
df.describe()

,ISO numeric country/territory code,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",Estimated prevalence of TB (all forms),"Estimated prevalence of TB (all forms), low bound","Estimated prevalence of TB (all forms), high bound","Estimated mortality of TB cases (all forms, excluding HIV) per 100 000 population",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
count,5120.000000,5120.000000,5.120000e+03,5120.000000,5100.000000,5100.000000,5.120000e+03,5.100000e+03,5.100000e+03,5120.000000,...,3645.000000,3642.000000,3642.000000,3645.000000,3642.000000,3642.000000,0.0,4671.000000,4671.000000,4671.000000
mean,433.576563,2001.549023,2.915671e+07,194.386100,101.815353,321.006367,6.654332e+04,4.615915e+04,9.319791e+04,20.174426,...,40.228274,33.892320,47.326378,6095.426979,5215.147573,7363.644445,NaN,68.217851,61.959409,75.854492
std,255.116018,6.933272,1.183725e+08,259.016385,145.259349,421.326139,3.249488e+05,2.711918e+05,3.938631e+05,32.893800,...,125.175567,105.557348,147.004849,22807.804792,19993.703601,26548.834113,NaN,25.465391,23.603155,29.277633
min,4.000000,1990.000000,1.129000e+03,0.000000,0.110000,0.770000,0.000000e+00,2.000000e-02,1.600000e-01,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,NaN,0.000000,0.000000,0.000000
25%,212.000000,1996.000000,5.601190e+05,23.000000,10.000000,43.000000,3.800000e+02,1.700000e+02,7.200000e+02,1.300000,...,0.190000,0.130000,0.240000,18.000000,12.000000,25.000000,NaN,52.000000,46.000000,59.000000
50%,430.000000,2002.000000,5.172118e+06,85.000000,40.000000,147.000000,4.300000e+03,2.100000e+03,7.700000e+03,5.400000,...,2.100000,1.700000,2.600000,170.000000,130.000000,220.000000,NaN,75.000000,68.000000,82.000000
75%,646.000000,2008.000000,1.752404e+07,272.000000,139.000000,447.000000,2.700000e+04,1.400000e+04,4.500000e+04,25.000000,...,14.000000,12.000000,17.000000,1700.000000,1400.000000,2000.000000,NaN,87.000000,77.000000,95.000000
max,894.000000,2013.000000,1.385567e+09,1762.000000,1316.000000,3038.000000,4.600000e+06,4.000000e+06,5.200000e+06,278.000000,...,1063.000000,981.000000,1438.000000,320000.000000,290000.000000,350000.000000,NaN,320.000000,270.000000,380.000000

In [18]:
df.drop(columns=['ISO 2-character country/territory code','ISO numeric country/territory code',
       'Estimated prevalence of TB (all forms) per 100 000 population, low bound',
       'Estimated prevalence of TB (all forms) per 100 000 population, high bound',
       'Estimated prevalence of TB (all forms), low bound',
       'Estimated prevalence of TB (all forms), high bound',
       'Estimated number of deaths from TB (all forms, excluding HIV), low bound',
       'Estimated number of deaths from TB (all forms, excluding HIV), high bound',
       ])

,Country or territory name,ISO 3-character country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,Estimated prevalence of TB (all forms),Method to derive prevalence estimates,"Estimated mortality of TB cases (all forms, excluding HIV) per 100 000 population","Estimated mortality of TB cases (all forms, excluding HIV), per 100 000 population, low bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AFG,EMR,1990,11731193,306.0,36000.0,predicted,37.0,24.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AFG,EMR,1991,12612043,343.0,43000.0,predicted,46.0,29.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AFG,EMR,1992,13811876,371.0,51000.0,predicted,54.0,34.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,EMR,1993,15175325,392.0,59000.0,predicted,60.0,38.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,EMR,1994,16485018,410.0,68000.0,predicted,65.0,41.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZWE,AFR,2009,12888918,449.0,58000.0,predicted,39.0,27.0,...,511.00,460.00,566.00,66000.0,59000.0,73000.0,NaN,50.0,45.0,54.0
5116,Zimbabwe,ZWE,AFR,2010,13076978,415.0,54000.0,predicted,36.0,25.0,...,487.00,433.00,545.00,64000.0,57000.0,71000.0,NaN,53.0,48.0,59.0
5117,Zimbabwe,ZWE,AFR,2011,13358738,417.0,56000.0,predicted,38.0,26.0,...,448.00,403.00,502.00,60000.0,54000.0,67000.0,NaN,48.0,43.0,53.0
5118,Zimbabwe,ZWE,AFR,2012,13724317,425.0,58000.0,predicted,41.0,27.0,...,411.00,362.00,471.00,56000.0,50000.0,65000.0,NaN,45.0,40.0,52.0
5119,Zimbabwe,ZWE,AFR,2013,14149648,409.0,58000.0,predicted,40.0,25.0,...,395.00,341.00,464.00,56000.0,48000.0,66000.0,NaN,42.0,36.0,49.0

In [19]:
df = df.iloc[:,1::3]

In [23]:
df.shape

(5120, 16)